#pragma once

#include <string>

#include <diagnostics/compilation_diagnostic.h>

enum compilation_error_code {
    ERR_SUCCESS = 0,
    ERR_ID_EXPECTED,
    ERR_LBRACE_EXPECTED,
    ERR_RBRACE_EXPECTED,
    ERR_LBRACKET_EXPECTED,
    ERR_RBRACKET_EXPECTED,
    ERR_LPAREN_EXPECTED,
    ERR_RPAREN_EXPECTED,
    ERR_SEMICOLON_EXPECTED,
    ERR_MODULE_NAME_EXPECTED,
    ERR_PARAM_TYPE_EXPECTED,
    ERR_PARAM_NAME_EXPECTED,
    ERR_FORWARD_DECL_UNSUPPORTED,
    ERR_UNEXPECTED_TOKEN_PRIMARY_EXPR,
    ERR_INCOMPLETE_ESCAPE_SEQ,
    ERR_CONSTRUCTOR_CALLS_ITSELF,
    ERR_MEMBER_DECLARATION_EXPECTED,
    ERR_NESTED_FUNCTION_NOT_ALLOWED,
    ERR_PARAM_VOID_TYPE,
    ERR_FUNCTION_ALREADY_DEFINED,
    ERR_NESTED_CONSTRUCTOR_NOT_ALLOWED,
    ERR_CONSTRUCTOR_OUTSIDE_TYPE,
    ERR_CONSTRUCTOR_OVERLOAD_EXISTS,
    ERR_VARIABLE_VOID_TYPE,
    ERR_VARIABLE_ALREADY_DECLARED_SCOPE,
    ERR_TYPE_ALREADY_DEFINED,
    ERR_NESTED_TYPE_DECLARATION_NOT_ALLOWED,
    ERR_STRUCT_CONTAINS_METHOD,
    ERR_INTERFACE_CONTAINS_CONSTRUCTOR,
    ERR_INTERFACE_CONTAINS_MEMBER_VAR,
    ERR_DUPLICATE_PARAMETER,
    ERR_UNKNOWN_IDENTIFIER,
    ERR_UNKNOWN_FUNCTION,
    ERR_UNKNOWN_TYPE,
    ERR_NO_MATCHING_CONSTRUCTOR,
    ERR_TOO_MANY_INITIALIZER_VALUES,
    ERR_TYPE_MISMATCH_INITIALIZER,
    ERR_INTERFACE_INITIALIZER,
    ERR_ARRAY_INITIALIZER_UNSUPPORTED,
    ERR_INVALID_INITIALIZER_LIST_USAGE,
    ERR_TYPE_ASSIGNMENT_MISMATCH,
    ERR_NO_MATCHING_OPERATOR,
    ERR_TYPE_NOT_DEFINED,
    ERR_MEMBER_NAME_EXPECTED,
    ERR_NO_MEMBER_WITH_NAME,
    ERR_NO_MATCHING_OPERATOR_BUILTIN_USER,
    ERR_LOGICAL_NOT_BOOLEAN_ONLY,
    ERR_NEGATE_NUMERIC_ONLY,
    ERR_INCREMENT_INTEGER_ONLY,
    ERR_DECREMENT_INTEGER_ONLY,
    ERR_BASE_NOT_INDEXABLE,
    ERR_INDEXER_NOT_INTEGER,
    ERR_NO_MATCHING_FUNCTION,
    ERR_NO_MATCHING_CONSTRUCTOR_ARGS,
    ERR_IF_CONDITION_NOT_BOOLEAN,
    ERR_FOR_CONDITION_NOT_BOOLEAN,
    ERR_WHILE_CONDITION_NOT_BOOLEAN,
    ERR_RETURN_OUTSIDE_FUNCTION,
    ERR_CONSTRUCTOR_RETURNS_VALUE,
    ERR_VOID_FUNCTION_RETURNS_VALUE,
    ERR_FUNCTION_MUST_RETURN_VALUE,
    ERR_FUNCTION_RETURN_TYPE_MISMATCH,
    ERR_NOT_ALL_PATHS_RETURN_VALUE,
    ERR_NO_METHOD_WITH_NAME,
    ERR_THIS_OUTSIDE_NONSTATIC_METHOD,
    ERR_INVALID_FLOAT_MULTIPLE_DECIMAL,
    ERR_INVALID_FLOAT_NO_DIGITS_AFTER_DECIMAL,
    ERR_UNTERMINATED_CHAR_LITERAL,
    ERR_UNTERMINATED_STRING_LITERAL,
    ERR_TOO_MANY_CHARS_IN_CHAR_LITERAL,
    ERR_EXPRESSION_EXPECTED,
    ERR_UNEXPECTED_IDENTIFIER,
    ERR_DECLARATION_EXPECTED,
    ERR_UNINITIALIZED_VARIABLE,
    ERR_MEMBER_ACCESS_ON_NONCOMPOSITE,
    ERR_PARAMETER_EXPECTED,
    ERR_NO_CONVERSION_EXISTS,
    ERR_CONVERSION_EXPLICIT_CAST_REQUIRED,
    ERR_CANNOT_OVERLOAD_BY_RETURN_TYPE,
    ERR_ENTRY_OVERLOADED,
    ERR_NO_MATCHING_METHOD,
    ERR_INTERNAL_ERROR,
    ERR_MODULE_NOT_FOUND,
    ERR_IMPORT_BAD_POS,
    ERR_NAME_COLLISION,
    ERR_UNTERMINATED_COMMENT,
    ERR_TYPENAME_EXPECTED,
    ERR_DUPLICATE_TYPE_MODIFIER,
    ERR_ADDRESS_OF_RVALUE,
    ERR_CANNOT_INFER_TYPE_NO_INIT,
    ERR_ARROW_EXPECTED,
    ERR_VAR_NAME_EXPECTED,
    ERR_CONST_NO_INITIALIZER,
    ERR_CONST_ASSIGNMENT,
    ERR_ASSIGNMENT_TO_RVALUE,
    ERR_ANGLE_LEFT_EXPECTED,
    ERR_ANGLE_RIGHT_EXPECTED,
    ERR_ONE_GENERIC_REQUIRED,
    ERR_DUPLICATE_GENERIC,
    ERR_INTERFACE_METHOD_HAS_BODY,
    ERR_INTERFACE_IS_DERIVED,
    ERR_STRUCT_IS_DERIVED,
    ERR_MULTIPLE_BASE_CLASSES,
    ERR_BASE_CLASS_NOT_FIRST,
    ERR_OVERRIDE_NOT_FOUND,
    ERR_NOT_ALL_INTERFACE_METHODS_IMPLEMENTED,
    ERR_COLON_EXPECTED,
    ERR_CIRCULAR_INHERITANCE,
    ERR_DEREFERENCE_OF_NON_POINTER,
    ERR_INVALID_ARRAY_INITIALIZER_USAGE,
    ERR_ARRAY_INITIALIZER_TYPE_MISMATCH,
    ERR_CANNOT_INFER_TYPE_UNKNOWN_INIT,
    ERR_VARIABLE_SHADOWS_GENERIC,
    ERR_GENERIC_SHADOWS_VARIABLE,
    ERR_AMBIGUOUS_CONSTRUCTOR_CALL,
    ERR_AMBIGUOUS_METHOD_CALL,
    ERR_AMBIGUOUS_FUNCTION_CALL,
    ERR_OVERRIDE_CANT_BE_GENERIC,
    ERR_CANNOT_INFER_TYPE,
    ERR_UNKNOWN_ESCAPE_SEQUENCE,
    ERR_BREAK_OUTSIDE_LOOP,
    ERR_GENERIC_ARGS_ON_NONCUSTOM_TYPE,
    ERR_GENERIC_ARGS_ON_NONGENERIC_TYPE,
    ERR_INCORRECT_NUMBER_OF_GENERIC_ARGS,
    ERR_ENUM_OPTION_NAME_EXPECTED,
    ERR_ENUM_ALREADY_DEFINED,
    ERR_NESTED_ENUM_NOT_ALLOWED,
    ERR_METHOD_ACCESS_ON_NONCOMPOSITE,
    ERR_NO_ENUM_MEMBER_WITH_NAME,
    ERR_ENUM_OPTION_ALREADY_DEFINED,
    ERR_ENUM_OPTION_MEMBER_ACCESS,
    ERR_ARRAY_SIZE_MUST_BE_INTEGER,
    ERR_ARRAY_SIZE_MUST_BE_CONSTANT,
    ERR_SCOPED_FUNCTION_NOT_MODULE,
    ERR_NO_MODULE_MEMBER_WITH_NAME,
    ERR_STATIC_ACCESS_INVALID,
    ERR_STATIC_ACCESS_NONSTATIC_MEMBER,
    ERR_NO_MEMBER_WITH_NAME_MODULE,
    ERR_NOT_A_TYPE,
    ERR_NAME_CONFLICT,
    ERR_CALL_ON_NON_FUNCTION,
    ERR_FIELD_CANNOT_BE_OWN_TYPE,
    ERR_MEMBER_ACCESS_NOT_ON_VARIABLE,
    ERR_NO_MATCHING_FUNCTION_GENERIC,
    ERR_DUPLICATE_MODIFIER,
    ERR_INVALID_MODIFIER_COMBINATION,
    ERR_INVALID_FUNCTION_MODIFIER,
    ERR_INVALID_VARIABLE_MODIFIER,
    ERR_INVALID_CLASS_MODIFIER,
    ERR_INVALID_STRUCT_MODIFIER,
    ERR_INVALID_INTERFACE_MODIFIER,
    ERR_INVALID_MODULE_MODIFIER,
    ERR_INVALID_ENUM_MODIFIER,
    ERR_EXTERN_FUNCTION_CANT_HAVE_BODY,
    ERR_FUNCTION_MUST_HAVE_BODY,
    ERR_ATTRIBUTE_EXPECTED,
    ERR_CANNOT_INFER_TYPE_NULL_INIT,
};

enum compilation_warning_code {
    WARN_VARIABLE_UNUSED,
    WARN_FUNCTION_UNUSED,
    WARN_TYPE_UNUSED,
    WARN_PARAMETER_UNUSED,
    WARN_VARIABLE_ASSIGNED_UNUSED,
    WARN_UNREACHABLE_CODE,
    WARN_CAST_UNNEEDED,
};

enum compilation_hint_code {
    HINT_CONDITIONAL_NOT_GUARANTEED_TO_RETURN,
    HINT_IMPLEMENT_INTERFACE_METHOD,
    HINT_USE_POINTER_INSTEAD_OF_OWN_TYPE,
    HINT_USE_EXTERN_MODIFIER,
};

struct error_catalog {
    static const compilation_diagnostic_info& get_error_info(compilation_error_code code) {
        static const compilation_diagnostic_info errors[] = {
            {"S001", "Identifier expected"},
            {"S002", "'{' expected"},
            {"S003", "'}' expected"},
            {"S004", "'[' expected"},
            {"S005", "']' expected"},
            {"S006", "'(' expected"},
            {"S007", "')' expected"},
            {"S008", "';' expected"},
            {"S009", "Expected module name"},
            {"S010", "Expected parameter type"},
            {"S011", "Expected parameter name"},
            {"S012", "Steel does not support forward declarations"},
            {"S013", "Unexpected token in primary expression"},
            {"S014", "Incomplete escape sequence in literal"},
            {"S015", "Constructor cannot call itself"},
            {"S016", "Member declaration expected"},
            {"S017", "Nested function is not allowed"},
            {"S018", "Parameters cannot be of type void"},
            {"S019", "Redefinition of function '{}' with identical signature"},
            {"S020", "Nested constructor is not allowed"},
            {"S021", "Constructor must be defined within a type"},
            {"S022", "Constructor with the same parameters already exists"},
            {"S023", "Variables cannot be of type void"},
            {"S024", "Variable '{}' already declared in the same scope"},
            {"S025", "Type '{}' already declared in the same scope"},
            {"S026", "Nested type declaration is not allowed"},
            {"S027", "Structs cannot contain methods"},
            {"S028", "Interfaces cannot contain constructors"},
            {"S029", "Interfaces cannot contain member variables"},
            {"S030", "Duplicate parameter '{}'"},
            {"S031", "Unknown identifier '{}'"},
            {"S032", "Unknown function '{}'"},
            {"S033", "Unknown type '{}'"},
            {"S034", "No constructor for type '{}' matches argument types provided"},
            {"S035", "Too many values in initializer list"},
            {"S036", "Type mismatch in initializer list, expected: '{}', got: '{}'"},
            {"S037", "Interface initializer is not allowed"},
            {"S038", "Array initializers are unsupported"},
            {"S039", "Initializer list can only be used with custom types"},
            {"S040", "Variable of type '{}' cannot be assigned a value of type \"{}\""},
            {"S041", "No built-in operator matches the types provided, types are '{}', '{}'"},
            {"S042", "The type '{}' is not defined"},
            {"S043", "Expected member name"},
            {"S044", "The type '{}' has no member named '{}'"},
            {"S045", "No built-in or user-defined operator matches the types provided, types are '{}', '{}'"},
            {"S046", "Logical NOT operator can only be applied to boolean expressions"},
            {"S047", "NEGATE operator can only be applied to integer or float expressions"},
            {"S048", "Increment operator can only be applied to integer expressions"},
            {"S049", "Decrement operator can only be applied to integer expressions"},
            {"S050", "Base expression is not indexable"},
            {"S051", "Indexer must be an integer expression"},
            {"S052", "No function '{}' matches the arguments provided"},
            {"S053", "No constructor for '{}' matches the arguments provided"},
            {"S054", "If statement condition must be a boolean expression"},
            {"S055", "For loop condition must be a boolean expression"},
            {"S056", "While loop condition must be a boolean expression"},
            {"S065", "Return statement outside of function or constructor"},
            {"S066", "Constructors cannot return a value"},
            {"S067", "Void function '{}' cannot return a value"},
            {"S068", "Non-void function '{}' must return a value"},
            {"S069", "Function '{}' returns type '{}' but got '{}'"},
            {"S070", "Not all code paths return a value"},
            {"S071", "The type '{}' has no method named '{}'"},
            {"S072", "'this' can only be used inside a non-static method or constructor"},
            {"S078", "Invalid float literal: multiple decimal points"},
            {"S079", "Invalid float literal: no digits after decimal point"},
            {"S080", "Unterminated char literal"},
            {"S081", "Unterminated string literal"},
            {"S082", "Too many characters in char literal"},
            {"S083", "Expected expression"},
            {"S084", "Unexpected identifier"},
            {"S085", "Expected a declaration"},
            {"S086", "Use of uninitialized variable '{}'"},
            {"S087", "Member access not allowed on non-composite type '{}'"},
            {"S088", "Expected parameter"},
            {"S089", "No built-in or user-defined conversion exists from '{}' to '{}'"},
            {"S090", "Conversion from '{}' to '{}' is explicit, did you forget to use a cast?"},
            {"S091", "Functions or methods cannot be overloaded by return type"},
            {"S092", "Only one entry point '{}' is allowed in a single program"},
            {"S093", "No method '{}' matches the arguments provided"},
            {"S094", "An internal compiler error occurred, phase: '{}', message: '{}'"},
            {"S095", "Module '{}' not found"},
            {"S096", "Import statements can only appear at top-level (outside all scopes)"},
            {"S097", "Ambiguous reference to '{}', could be '{}'"},
            {"S098", "Unterminated mutli-line comment"},
            {"S099", "Type name expected"},
            {"S100", "Duplicate type modifier"},
            {"S101", "Cannot get memory address of non-variable"},
            {"S102", "Variable type cannot be inferred without an initializer"},
            {"S103", "'->' expected"},
            {"S104", "Variable name expected"},
            {"S105", "A const variable must have an initializer"},
            {"S106", "A const variable can only be assigned a value at initialization"},
            {"S107", "A constant value cannot be assigned"},
            {"S108", "'<' expected"},
            {"S109", "'>' expected"},
            {"S110", "At least one generic parameter is required"},
            {"S111", "Duplicate generic parameter '{}'"},
            {"S112", "Interface methods cannot have a body"},
            {"S113", "An interface cannot be derived from any type"},
            {"S114", "Structs cannot be derived from any type"},
            {"S115", "Classes can only derive from one base class"},
            {"S116", "The base class '{}' must be first in the implementation list"},
            {"S117", "No overridden method '{}' found in any base class or interface"},
            {"S118", "Class '{}' does not implement all required interface methods (implemented: {}, total: {})"},
            {"S119", "':' expected"},
            {"S120", "Circular inheritance detected. Class '{}' eventually inherits from itself: {}"},
            {"S121", "Cannot dereference object with non-pointer type"},
            {"S122", "Array initializer can only be used to initialize arrays"},
            {"S123", "Type mismatch in array initializer. Expected '{}' but got '{}'"},
            {"S124", "Cannot infer type from initializer"},
            {"S125", "Local variable '{}' shadows generic parameter '{}'"},
            {"S126", "Generic parameter '{}' shadows local variable '{}'"},
            {"S127", "Ambiguous constructor call to '{}' with the given argument types"},
            {"S128", "Ambiguous method call to '{}' with the given argument types"},
            {"S129", "Ambiguous function call to '{}' with the given argument types"},
            {"S130", "Generic functions cannot be marked as 'override'"},
            {"S131", "Failed to infer type"},
            {"S132", "Invalid escape sequence: '{}'"},
            {"S133", "Break statement outside loop"},
            {"S134", "Generic arguments cannot be used on non-custom type '{}'"},
            {"S135", "Generic arguments cannot be used on non-generic type '{}'"},
            {"S136", "Missing required generic arguments for generic type '{}', types are: {}"},
            {"S137", "Expected an identifier for enum option"},
            {"S138", "Enum '{}' already declared in the same scope"},
            {"S139", "Enum inside enum is not allowed"},
            {"S140", "Method access not allowed on non-composite type '{}'"},
            {"S141", "The enum '{}' does not contain an option named '{}'"},
            {"S142", "The enum '{}' already contains an option named '{}'"},
            {"S143", "Member access not allowed on enum option '{}'"},
            {"S144", "Array size must be an integer"},
            {"S145", "Array size must be a constant compile-time computable value"},
            {"S146", "Scoped function calls (e.g. scope::func()) can only be used on modules"},
            {"S147", "The module '{}' has no member named '{}'"},
            {"S148", "Static access not allowed on {} '{}'"},
            {"S149", "An object instance is required to access non-static member '{}'"},
            {"S150", "The module '{}' has no member named '{}'"},
            {"S151", "'{}' is not a type"},
            {"S152", "Cannot declare {} '{}' because a {} with the same name already exists in this scope"},
            {"S153", "Cannot call non-function"},
            {"S154", "The recursive field '{}' of type '{}' has infinite size"},
            {"S155", "Non-static member access only allowed on variables"},
            {"S156", "No overload of function '{}' accepts {} generic argument(s)"},
            {"S157", "Duplicate modifier '{}'"},
            {"S158", "Invalid combination of modifiers"},
            {"S159", "Invalid function modifier '{}'"},
            {"S160", "Invalid variable modifier '{}'"},
            {"S161", "Invalid class modifier '{}'"},
            {"S162", "Invalid struct modifier '{}'"},
            {"S163", "Invalid interface modifier '{}'"},
            {"S164", "Invalid module modifier '{}'"},
            {"S165", "Invalid enum modifier '{}'"},
            {"S166", "Function '{}' cannot have a body as it has been marked extern"},
            {"S167", "Function '{}' must have a body as it has not been marked extern"},
            {"S168", "Attribute name expected"},
            {"S169", "Cannot infer type from null"},
        };
        return errors[code - 1 /* -1 to avoid ERR_SUCCESS */];
    }

    static const compilation_diagnostic_info& get_warning_info(compilation_warning_code code) {
        static const compilation_diagnostic_info warnings[] = {
            {"SW01", "Variable \"{}\" is declared but never used"},
            {"SW02", "Function \"{}\" is declared but never used"},
            {"SW03", "Type \"{}\" is declared but never used"},
            {"SW04", "Parameter \"{}\" is declared but never used"},
            {"SW05", "Variable \"{}\" is assigned a value but never used"},
            {"SW10", "Unreachable code detected"},
            {"SW11", "An implicit cast exists from '{}' to '{}', an explicit cast is not needed"},
        };
        return warnings[code];
    }

    static const compilation_diagnostic_info& get_hint_info(compilation_hint_code code) {
        static const compilation_diagnostic_info hints[] = {
            {"SH01", "Conditional returns are not guaranteed to return, ensure an unconditional return is present incase all conditional returns are not executed"},
            {"SH02", "Implement required interface method: '{}'"},
            {"SH03", "To store objects of a type within itself, consider using a pointer ({}*)"},
            {"SH04", "To declare a function that exists outside of your program, consider using the 'extern' keyword. E.g., 'extern func {}(...);'"},
        };
        return hints[code];
    }
};
